### ISSUE TITLE
cannot backup keys

### ISSUE THREAD

**Issue by umk0m1qk** [verbiricha/habla.news#174]
Receive the following error when trying to back up keys. Brave [Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit)

**Application error: a client-side exception has occurred (see the browser console for more information).**

Error: radix2.encode input should be Uint8Array
    at Object.encode [as toWords] (_app-bcafe889c00afd18.js:301:323375)
    at iy (_app-bcafe889c00afd18.js:2348:271667)
    at im (_app-bcafe889c00afd18.js:2348:271735)
    at Object.ih (_app-bcafe889c00afd18.js:2348:271525)
    at x (4523.6ea633d273fbe2d4.js:1:1977)
    at ak (framework-3c0d1ce97e33029f.js:9:60903)
    at i (framework-3c0d1ce97e33029f.js:9:119424)
    at oD (framework-3c0d1ce97e33029f.js:9:99077)
    at framework-3c0d1ce97e33029f.js:9:98944
    at oO (framework-3c0d1ce97e33029f.js:9:98951)
Z @ main-06ce65b74259da46.js:1
fn @ main-06ce65b74259da46.js:1
componentDidCatch @ main-06ce65b74259da46.js:1
(anonymous) @ framework-3c0d1ce97e33029f.js:9
lW @ framework-3c0d1ce97e33029f.js:9
uX @ framework-3c0d1ce97e33029f.js:9
e @ framework-3c0d1ce97e33029f.js:9
(anonymous) @ framework-3c0d1ce97e33029f.js:9
oU @ framework-3c0d1ce97e33029f.js:9
ox @ framework-3c0d1ce97e33029f.js:9
x @ framework-3c0d1ce97e33029f.js:33
T @ framework-3c0d1ce97e33029f.js:33

A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z @ main-06ce65b74259da46.js:1
fn @ main-06ce65b74259da46.js:1
componentDidCatch @ main-06ce65b74259da46.js:1
(anonymous) @ framework-3c0d1ce97e33029f.js:9
lW @ framework-3c0d1ce97e33029f.js:9
uX @ framework-3c0d1ce97e33029f.js:9
e @ framework-3c0d1ce97e33029f.js:9
(anonymous) @ framework-3c0d1ce97e33029f.js:9
oU @ framework-3c0d1ce97e33029f.js:9
ox @ framework-3c0d1ce97e33029f.js:9
x @ framework-3c0d1ce97e33029f.js:33
T @ framework-3c0d1ce97e33029f.js:33

**Comment by partyp** [comment]
Ditto, I can not seem to get anyone on the profile setup. All the buttons lead to blank pages or this error you mentioned for the key backups "https://habla.news/onboarding/backup"
